language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

script:
  - julia --code-coverage=user --inline=no -e 'using Pkg; Pkg.add(Pkg.PackageSpec(path=pwd())); Pkg.build("PairwiseListMatrices"); Pkg.test("PairwiseListMatrices", coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Plots"); Pkg.add("GR"); Pkg.add("DataFrames"); Pkg.add("CSV")' # DocDeps
  - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.add("Documenter")'
  - julia --code-coverage=user --inline=no -e 'include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
