language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

before_install:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
 - julia --check-bounds=yes --inline=yes --code-coverage=user -e 'using InteractiveUtils; using Pkg; versioninfo();  Pkg.add(Pkg.PackageSpec(path=pwd())); Pkg.build("PairwiseListMatrices"); Pkg.test("PairwiseListMatrices", coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg; Pkg.add("Coverage")' # Coverage
  - julia -e 'using Pkg; Pkg.add("Plots"); Pkg.add("GR"); using Plots, GR' # Plots
  - julia -e 'using Pkg; Pkg.add("DataFrames"); Pkg.add("CSV");' # DataFrames
  # Documentation and DocTests
  - julia --code-coverage=user -e 'import PairwiseListMatrices; include(joinpath(dirname(pathof(PairwiseListMatrices)), "..", "docs", "make.jl"))'
  # Coverage
  - julia -e 'using Pkg; using PairwiseListMatrices; pkdir = dirname(pathof(PairwiseListMatrices)); println(pkdir); cd(pkdir); using Coverage; Coveralls.submit(Coveralls.process_folder())'
