language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Plots"); Pkg.add("GR"); Pkg.add("DataFrames"); Pkg.add("CSV")' # DocDeps
  - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.add("Documenter")'
  - julia -e --code-coverage=user --inline=no 'include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
